<template>
    <svg
        viewBox="0 0 48 48"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        class="w-12 h-12"
    >
        <rect
            width="48"
            height="48"
            rx="24"
            class="fill-[#148EF8]"
        />
        <rect
            x="23"
            y="19"
            width="3"
            height="13"
            rx="1.5"
            class="fill-[#A0D5FF]"
        />
        <rect
            x="23"
            y="14"
            width="3"
            height="3"
            rx="1.5"
            class="fill-[#A0D5FF]"
        />
    </svg>
</template>
