name: Build and Zip on Feature/Fix Branches

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Build project
        run: |
          npm run build

      - name: Create zip archive
        run: |
          mkdir -p artifacts
          zip -r "artifacts/dist_${GITHUB_REF##*/}.zip" ./dist

      - name: Upload zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-zip
          path: artifacts/