name: Build and Zip on Feature/Fix Branches

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Load .env variables
        run: |
          set -o allexport
          source .env
          set +o allexport
        shell: bash

      - name: Build project
        run: |
          npm run build

      - name: Create zip archive
        run: |
          mkdir -p artifacts
          TIMESTAMP=$(date +%s%3N)
          zip -r "artifacts/dist_${VITE_INTERFACE_VERSION}_${VITE_IP}_${TIMESTAMP}.zip" ./dist

      - name: Upload zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-zip
          path: artifacts/