name: Build and Zip on Feature/Fix Branches

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Load .env variables
        id: load_env
        run: |
          set -o allexport
          source .env
          set +o allexport
          echo "VITE_INTERFACE_VERSION=$(echo $VITE_INTERFACE_VERSION | tr -d '\r')" >> $GITHUB_ENV
          echo "VITE_IP=$(echo $VITE_IP | tr -d '\r')" >> $GITHUB_ENV
          echo "Loaded VITE_INTERFACE_VERSION=${VITE_INTERFACE_VERSION}"
          echo "Loaded VITE_IP=${VITE_IP}"
        shell: bash

      - name: Build project
        run: |
          npm run build

      - name: Create zip archive
        id: create_zip
        run: |
          TIMESTAMP=$(date +%s%3N)
          ZIP_NAME="dist_${{ env.VITE_INTERFACE_VERSION }}_${{ env.VITE_IP }}_${TIMESTAMP}.zip"
          echo "zip name: $ZIP_NAME"
          zip -r "$ZIP_NAME" ./dist
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}
